#-----------------------------FP SENSOR---------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_FP)                  += fpc1020/
obj-$(CONFIG_NUBIA_SENSORS_FP)                  += gf5228/
obj-$(CONFIG_NUBIA_FP_AUTODETECT)		        += fp_autodetect.o
#---------------------------PROX SENSOR---------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_PROX_PA224)			+= txc_pa224.o
#---------------------------RGB SENSOR----------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_RGB_BH1745)			+= rohm_bh1745.o
#---------------------------HALL SENSOR---------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_HALL_DEVICE)  		+= hall_device.o
#--------------------------IR Remote------------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_IR_REMOTE_I_THREE)		+= i_three.o
#--------------------------vibrator-------------------------------------#
obj-$(CONFIG_NUBIA_SENSOR_VIBRATOR)			+= drv2605/
